// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "featuredatumplane.h"

namespace prj
{
  namespace srl
  {
    // DatumPlanePlanarOffset
    // 

    const DatumPlanePlanarOffset::FaceIdType& DatumPlanePlanarOffset::
    faceId () const
    {
      return this->faceId_.get ();
    }

    DatumPlanePlanarOffset::FaceIdType& DatumPlanePlanarOffset::
    faceId ()
    {
      return this->faceId_.get ();
    }

    void DatumPlanePlanarOffset::
    faceId (const FaceIdType& x)
    {
      this->faceId_.set (x);
    }

    void DatumPlanePlanarOffset::
    faceId (::std::unique_ptr< FaceIdType > x)
    {
      this->faceId_.set (std::move (x));
    }

    const DatumPlanePlanarOffset::FaceIdType& DatumPlanePlanarOffset::
    faceId_default_value ()
    {
      return faceId_default_value_;
    }

    const DatumPlanePlanarOffset::OffsetType& DatumPlanePlanarOffset::
    offset () const
    {
      return this->offset_.get ();
    }

    DatumPlanePlanarOffset::OffsetType& DatumPlanePlanarOffset::
    offset ()
    {
      return this->offset_.get ();
    }

    void DatumPlanePlanarOffset::
    offset (const OffsetType& x)
    {
      this->offset_.set (x);
    }

    void DatumPlanePlanarOffset::
    offset (::std::unique_ptr< OffsetType > x)
    {
      this->offset_.set (std::move (x));
    }


    // DatumPlanePlanarCenter
    // 

    const DatumPlanePlanarCenter::FaceId1Type& DatumPlanePlanarCenter::
    faceId1 () const
    {
      return this->faceId1_.get ();
    }

    DatumPlanePlanarCenter::FaceId1Type& DatumPlanePlanarCenter::
    faceId1 ()
    {
      return this->faceId1_.get ();
    }

    void DatumPlanePlanarCenter::
    faceId1 (const FaceId1Type& x)
    {
      this->faceId1_.set (x);
    }

    void DatumPlanePlanarCenter::
    faceId1 (::std::unique_ptr< FaceId1Type > x)
    {
      this->faceId1_.set (std::move (x));
    }

    const DatumPlanePlanarCenter::FaceId1Type& DatumPlanePlanarCenter::
    faceId1_default_value ()
    {
      return faceId1_default_value_;
    }

    const DatumPlanePlanarCenter::FaceId2Type& DatumPlanePlanarCenter::
    faceId2 () const
    {
      return this->faceId2_.get ();
    }

    DatumPlanePlanarCenter::FaceId2Type& DatumPlanePlanarCenter::
    faceId2 ()
    {
      return this->faceId2_.get ();
    }

    void DatumPlanePlanarCenter::
    faceId2 (const FaceId2Type& x)
    {
      this->faceId2_.set (x);
    }

    void DatumPlanePlanarCenter::
    faceId2 (::std::unique_ptr< FaceId2Type > x)
    {
      this->faceId2_.set (std::move (x));
    }

    const DatumPlanePlanarCenter::FaceId2Type& DatumPlanePlanarCenter::
    faceId2_default_value ()
    {
      return faceId2_default_value_;
    }


    // DatumPlanePlanarParallelThroughEdge
    // 

    const DatumPlanePlanarParallelThroughEdge::FaceIdType& DatumPlanePlanarParallelThroughEdge::
    faceId () const
    {
      return this->faceId_.get ();
    }

    DatumPlanePlanarParallelThroughEdge::FaceIdType& DatumPlanePlanarParallelThroughEdge::
    faceId ()
    {
      return this->faceId_.get ();
    }

    void DatumPlanePlanarParallelThroughEdge::
    faceId (const FaceIdType& x)
    {
      this->faceId_.set (x);
    }

    void DatumPlanePlanarParallelThroughEdge::
    faceId (::std::unique_ptr< FaceIdType > x)
    {
      this->faceId_.set (std::move (x));
    }

    const DatumPlanePlanarParallelThroughEdge::FaceIdType& DatumPlanePlanarParallelThroughEdge::
    faceId_default_value ()
    {
      return faceId_default_value_;
    }

    const DatumPlanePlanarParallelThroughEdge::EdgeIdType& DatumPlanePlanarParallelThroughEdge::
    edgeId () const
    {
      return this->edgeId_.get ();
    }

    DatumPlanePlanarParallelThroughEdge::EdgeIdType& DatumPlanePlanarParallelThroughEdge::
    edgeId ()
    {
      return this->edgeId_.get ();
    }

    void DatumPlanePlanarParallelThroughEdge::
    edgeId (const EdgeIdType& x)
    {
      this->edgeId_.set (x);
    }

    void DatumPlanePlanarParallelThroughEdge::
    edgeId (::std::unique_ptr< EdgeIdType > x)
    {
      this->edgeId_.set (std::move (x));
    }

    const DatumPlanePlanarParallelThroughEdge::EdgeIdType& DatumPlanePlanarParallelThroughEdge::
    edgeId_default_value ()
    {
      return edgeId_default_value_;
    }


    // SolverChoice
    // 

    const SolverChoice::OffsetOptional& SolverChoice::
    offset () const
    {
      return this->offset_;
    }

    SolverChoice::OffsetOptional& SolverChoice::
    offset ()
    {
      return this->offset_;
    }

    void SolverChoice::
    offset (const OffsetType& x)
    {
      this->offset_.set (x);
    }

    void SolverChoice::
    offset (const OffsetOptional& x)
    {
      this->offset_ = x;
    }

    void SolverChoice::
    offset (::std::unique_ptr< OffsetType > x)
    {
      this->offset_.set (std::move (x));
    }

    const SolverChoice::CenterOptional& SolverChoice::
    center () const
    {
      return this->center_;
    }

    SolverChoice::CenterOptional& SolverChoice::
    center ()
    {
      return this->center_;
    }

    void SolverChoice::
    center (const CenterType& x)
    {
      this->center_.set (x);
    }

    void SolverChoice::
    center (const CenterOptional& x)
    {
      this->center_ = x;
    }

    void SolverChoice::
    center (::std::unique_ptr< CenterType > x)
    {
      this->center_.set (std::move (x));
    }

    const SolverChoice::ParallelThroughEdgeOptional& SolverChoice::
    parallelThroughEdge () const
    {
      return this->parallelThroughEdge_;
    }

    SolverChoice::ParallelThroughEdgeOptional& SolverChoice::
    parallelThroughEdge ()
    {
      return this->parallelThroughEdge_;
    }

    void SolverChoice::
    parallelThroughEdge (const ParallelThroughEdgeType& x)
    {
      this->parallelThroughEdge_.set (x);
    }

    void SolverChoice::
    parallelThroughEdge (const ParallelThroughEdgeOptional& x)
    {
      this->parallelThroughEdge_ = x;
    }

    void SolverChoice::
    parallelThroughEdge (::std::unique_ptr< ParallelThroughEdgeType > x)
    {
      this->parallelThroughEdge_.set (std::move (x));
    }


    // FeatureDatumPlane
    // 

    const FeatureDatumPlane::FeatureBaseType& FeatureDatumPlane::
    featureBase () const
    {
      return this->featureBase_.get ();
    }

    FeatureDatumPlane::FeatureBaseType& FeatureDatumPlane::
    featureBase ()
    {
      return this->featureBase_.get ();
    }

    void FeatureDatumPlane::
    featureBase (const FeatureBaseType& x)
    {
      this->featureBase_.set (x);
    }

    void FeatureDatumPlane::
    featureBase (::std::unique_ptr< FeatureBaseType > x)
    {
      this->featureBase_.set (std::move (x));
    }

    const FeatureDatumPlane::SolverChoiceType& FeatureDatumPlane::
    solverChoice () const
    {
      return this->solverChoice_.get ();
    }

    FeatureDatumPlane::SolverChoiceType& FeatureDatumPlane::
    solverChoice ()
    {
      return this->solverChoice_.get ();
    }

    void FeatureDatumPlane::
    solverChoice (const SolverChoiceType& x)
    {
      this->solverChoice_.set (x);
    }

    void FeatureDatumPlane::
    solverChoice (::std::unique_ptr< SolverChoiceType > x)
    {
      this->solverChoice_.set (std::move (x));
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace prj
{
  namespace srl
  {
    // DatumPlanePlanarOffset
    //

    const DatumPlanePlanarOffset::FaceIdType DatumPlanePlanarOffset::faceId_default_value_ (
      "00000000-0000-0000-0000-000000000000");

    DatumPlanePlanarOffset::
    DatumPlanePlanarOffset (const FaceIdType& faceId,
                            const OffsetType& offset)
    : ::xml_schema::Type (),
      faceId_ (faceId, this),
      offset_ (offset, this)
    {
    }

    DatumPlanePlanarOffset::
    DatumPlanePlanarOffset (const FaceIdType& faceId,
                            ::std::unique_ptr< OffsetType > offset)
    : ::xml_schema::Type (),
      faceId_ (faceId, this),
      offset_ (std::move (offset), this)
    {
    }

    DatumPlanePlanarOffset::
    DatumPlanePlanarOffset (const DatumPlanePlanarOffset& x,
                            ::xml_schema::Flags f,
                            ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      faceId_ (x.faceId_, f, this),
      offset_ (x.offset_, f, this)
    {
    }

    DatumPlanePlanarOffset::
    DatumPlanePlanarOffset (const ::xercesc::DOMElement& e,
                            ::xml_schema::Flags f,
                            ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      faceId_ (this),
      offset_ (this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void DatumPlanePlanarOffset::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // faceId
        //
        if (n.name () == "faceId" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< FaceIdType > r (
            FaceIdTraits::create (i, f, this));

          if (!faceId_.present ())
          {
            this->faceId_.set (::std::move (r));
            continue;
          }
        }

        // offset
        //
        if (n.name () == "offset" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< OffsetType > r (
            OffsetTraits::create (i, f, this));

          if (!offset_.present ())
          {
            this->offset_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!faceId_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "faceId",
          "");
      }

      if (!offset_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "offset",
          "");
      }
    }

    DatumPlanePlanarOffset* DatumPlanePlanarOffset::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class DatumPlanePlanarOffset (*this, f, c);
    }

    DatumPlanePlanarOffset& DatumPlanePlanarOffset::
    operator= (const DatumPlanePlanarOffset& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::Type& > (*this) = x;
        this->faceId_ = x.faceId_;
        this->offset_ = x.offset_;
      }

      return *this;
    }

    DatumPlanePlanarOffset::
    ~DatumPlanePlanarOffset ()
    {
    }

    // DatumPlanePlanarCenter
    //

    const DatumPlanePlanarCenter::FaceId1Type DatumPlanePlanarCenter::faceId1_default_value_ (
      "00000000-0000-0000-0000-000000000000");

    const DatumPlanePlanarCenter::FaceId2Type DatumPlanePlanarCenter::faceId2_default_value_ (
      "00000000-0000-0000-0000-000000000000");

    DatumPlanePlanarCenter::
    DatumPlanePlanarCenter (const FaceId1Type& faceId1,
                            const FaceId2Type& faceId2)
    : ::xml_schema::Type (),
      faceId1_ (faceId1, this),
      faceId2_ (faceId2, this)
    {
    }

    DatumPlanePlanarCenter::
    DatumPlanePlanarCenter (const DatumPlanePlanarCenter& x,
                            ::xml_schema::Flags f,
                            ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      faceId1_ (x.faceId1_, f, this),
      faceId2_ (x.faceId2_, f, this)
    {
    }

    DatumPlanePlanarCenter::
    DatumPlanePlanarCenter (const ::xercesc::DOMElement& e,
                            ::xml_schema::Flags f,
                            ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      faceId1_ (this),
      faceId2_ (this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void DatumPlanePlanarCenter::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // faceId1
        //
        if (n.name () == "faceId1" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< FaceId1Type > r (
            FaceId1Traits::create (i, f, this));

          if (!faceId1_.present ())
          {
            this->faceId1_.set (::std::move (r));
            continue;
          }
        }

        // faceId2
        //
        if (n.name () == "faceId2" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< FaceId2Type > r (
            FaceId2Traits::create (i, f, this));

          if (!faceId2_.present ())
          {
            this->faceId2_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!faceId1_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "faceId1",
          "");
      }

      if (!faceId2_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "faceId2",
          "");
      }
    }

    DatumPlanePlanarCenter* DatumPlanePlanarCenter::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class DatumPlanePlanarCenter (*this, f, c);
    }

    DatumPlanePlanarCenter& DatumPlanePlanarCenter::
    operator= (const DatumPlanePlanarCenter& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::Type& > (*this) = x;
        this->faceId1_ = x.faceId1_;
        this->faceId2_ = x.faceId2_;
      }

      return *this;
    }

    DatumPlanePlanarCenter::
    ~DatumPlanePlanarCenter ()
    {
    }

    // DatumPlanePlanarParallelThroughEdge
    //

    const DatumPlanePlanarParallelThroughEdge::FaceIdType DatumPlanePlanarParallelThroughEdge::faceId_default_value_ (
      "00000000-0000-0000-0000-000000000000");

    const DatumPlanePlanarParallelThroughEdge::EdgeIdType DatumPlanePlanarParallelThroughEdge::edgeId_default_value_ (
      "00000000-0000-0000-0000-000000000000");

    DatumPlanePlanarParallelThroughEdge::
    DatumPlanePlanarParallelThroughEdge (const FaceIdType& faceId,
                                         const EdgeIdType& edgeId)
    : ::xml_schema::Type (),
      faceId_ (faceId, this),
      edgeId_ (edgeId, this)
    {
    }

    DatumPlanePlanarParallelThroughEdge::
    DatumPlanePlanarParallelThroughEdge (const DatumPlanePlanarParallelThroughEdge& x,
                                         ::xml_schema::Flags f,
                                         ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      faceId_ (x.faceId_, f, this),
      edgeId_ (x.edgeId_, f, this)
    {
    }

    DatumPlanePlanarParallelThroughEdge::
    DatumPlanePlanarParallelThroughEdge (const ::xercesc::DOMElement& e,
                                         ::xml_schema::Flags f,
                                         ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      faceId_ (this),
      edgeId_ (this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void DatumPlanePlanarParallelThroughEdge::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // faceId
        //
        if (n.name () == "faceId" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< FaceIdType > r (
            FaceIdTraits::create (i, f, this));

          if (!faceId_.present ())
          {
            this->faceId_.set (::std::move (r));
            continue;
          }
        }

        // edgeId
        //
        if (n.name () == "edgeId" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< EdgeIdType > r (
            EdgeIdTraits::create (i, f, this));

          if (!edgeId_.present ())
          {
            this->edgeId_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!faceId_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "faceId",
          "");
      }

      if (!edgeId_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "edgeId",
          "");
      }
    }

    DatumPlanePlanarParallelThroughEdge* DatumPlanePlanarParallelThroughEdge::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class DatumPlanePlanarParallelThroughEdge (*this, f, c);
    }

    DatumPlanePlanarParallelThroughEdge& DatumPlanePlanarParallelThroughEdge::
    operator= (const DatumPlanePlanarParallelThroughEdge& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::Type& > (*this) = x;
        this->faceId_ = x.faceId_;
        this->edgeId_ = x.edgeId_;
      }

      return *this;
    }

    DatumPlanePlanarParallelThroughEdge::
    ~DatumPlanePlanarParallelThroughEdge ()
    {
    }

    // SolverChoice
    //

    SolverChoice::
    SolverChoice ()
    : ::xml_schema::Type (),
      offset_ (this),
      center_ (this),
      parallelThroughEdge_ (this)
    {
    }

    SolverChoice::
    SolverChoice (const SolverChoice& x,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      offset_ (x.offset_, f, this),
      center_ (x.center_, f, this),
      parallelThroughEdge_ (x.parallelThroughEdge_, f, this)
    {
    }

    SolverChoice::
    SolverChoice (const ::xercesc::DOMElement& e,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      offset_ (this),
      center_ (this),
      parallelThroughEdge_ (this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void SolverChoice::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // offset
        //
        if (n.name () == "offset" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< OffsetType > r (
            OffsetTraits::create (i, f, this));

          if (!this->offset_)
          {
            this->offset_.set (::std::move (r));
            continue;
          }
        }

        // center
        //
        if (n.name () == "center" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< CenterType > r (
            CenterTraits::create (i, f, this));

          if (!this->center_)
          {
            this->center_.set (::std::move (r));
            continue;
          }
        }

        // parallelThroughEdge
        //
        if (n.name () == "parallelThroughEdge" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< ParallelThroughEdgeType > r (
            ParallelThroughEdgeTraits::create (i, f, this));

          if (!this->parallelThroughEdge_)
          {
            this->parallelThroughEdge_.set (::std::move (r));
            continue;
          }
        }

        break;
      }
    }

    SolverChoice* SolverChoice::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class SolverChoice (*this, f, c);
    }

    SolverChoice& SolverChoice::
    operator= (const SolverChoice& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::Type& > (*this) = x;
        this->offset_ = x.offset_;
        this->center_ = x.center_;
        this->parallelThroughEdge_ = x.parallelThroughEdge_;
      }

      return *this;
    }

    SolverChoice::
    ~SolverChoice ()
    {
    }

    // FeatureDatumPlane
    //

    FeatureDatumPlane::
    FeatureDatumPlane (const FeatureBaseType& featureBase,
                       const SolverChoiceType& solverChoice)
    : ::xml_schema::Type (),
      featureBase_ (featureBase, this),
      solverChoice_ (solverChoice, this)
    {
    }

    FeatureDatumPlane::
    FeatureDatumPlane (::std::unique_ptr< FeatureBaseType > featureBase,
                       ::std::unique_ptr< SolverChoiceType > solverChoice)
    : ::xml_schema::Type (),
      featureBase_ (std::move (featureBase), this),
      solverChoice_ (std::move (solverChoice), this)
    {
    }

    FeatureDatumPlane::
    FeatureDatumPlane (const FeatureDatumPlane& x,
                       ::xml_schema::Flags f,
                       ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      featureBase_ (x.featureBase_, f, this),
      solverChoice_ (x.solverChoice_, f, this)
    {
    }

    FeatureDatumPlane::
    FeatureDatumPlane (const ::xercesc::DOMElement& e,
                       ::xml_schema::Flags f,
                       ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      featureBase_ (this),
      solverChoice_ (this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void FeatureDatumPlane::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // featureBase
        //
        if (n.name () == "featureBase" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< FeatureBaseType > r (
            FeatureBaseTraits::create (i, f, this));

          if (!featureBase_.present ())
          {
            this->featureBase_.set (::std::move (r));
            continue;
          }
        }

        // solverChoice
        //
        if (n.name () == "solverChoice" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< SolverChoiceType > r (
            SolverChoiceTraits::create (i, f, this));

          if (!solverChoice_.present ())
          {
            this->solverChoice_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!featureBase_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "featureBase",
          "");
      }

      if (!solverChoice_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "solverChoice",
          "");
      }
    }

    FeatureDatumPlane* FeatureDatumPlane::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class FeatureDatumPlane (*this, f, c);
    }

    FeatureDatumPlane& FeatureDatumPlane::
    operator= (const FeatureDatumPlane& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::Type& > (*this) = x;
        this->featureBase_ = x.featureBase_;
        this->solverChoice_ = x.solverChoice_;
      }

      return *this;
    }

    FeatureDatumPlane::
    ~FeatureDatumPlane ()
    {
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace prj
{
  namespace srl
  {
    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (const ::std::string& u,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      return ::std::unique_ptr< ::prj::srl::FeatureDatumPlane > (
        ::prj::srl::datumPlane (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (const ::std::string& u,
                ::xml_schema::ErrorHandler& h,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::prj::srl::FeatureDatumPlane > (
        ::prj::srl::datumPlane (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (const ::std::string& u,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::prj::srl::FeatureDatumPlane > (
        ::prj::srl::datumPlane (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::std::istream& is,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::prj::srl::datumPlane (isrc, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::std::istream& is,
                ::xml_schema::ErrorHandler& h,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::prj::srl::datumPlane (isrc, h, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::std::istream& is,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::prj::srl::datumPlane (isrc, h, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::std::istream& is,
                const ::std::string& sid,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::prj::srl::datumPlane (isrc, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::std::istream& is,
                const ::std::string& sid,
                ::xml_schema::ErrorHandler& h,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::prj::srl::datumPlane (isrc, h, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::std::istream& is,
                const ::std::string& sid,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::prj::srl::datumPlane (isrc, h, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::xercesc::InputSource& i,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      return ::std::unique_ptr< ::prj::srl::FeatureDatumPlane > (
        ::prj::srl::datumPlane (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::xercesc::InputSource& i,
                ::xml_schema::ErrorHandler& h,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::prj::srl::FeatureDatumPlane > (
        ::prj::srl::datumPlane (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::xercesc::InputSource& i,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::prj::srl::FeatureDatumPlane > (
        ::prj::srl::datumPlane (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (const ::xercesc::DOMDocument& doc,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties& p)
    {
      if (f & ::xml_schema::Flags::keep_dom)
      {
        ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
          static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

        return ::std::unique_ptr< ::prj::srl::FeatureDatumPlane > (
          ::prj::srl::datumPlane (
            std::move (d), f | ::xml_schema::Flags::own_dom, p));
      }

      const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == "datumPlane" &&
          n.namespace_ () == "http://www.cadseer.com/prj/srl")
      {
        ::std::unique_ptr< ::prj::srl::FeatureDatumPlane > r (
          ::xsd::cxx::tree::traits< ::prj::srl::FeatureDatumPlane, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "datumPlane",
        "http://www.cadseer.com/prj/srl");
    }

    ::std::unique_ptr< ::prj::srl::FeatureDatumPlane >
    datumPlane (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                ::xml_schema::Flags f,
                const ::xml_schema::Properties&)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
        ((f & ::xml_schema::Flags::keep_dom) &&
         !(f & ::xml_schema::Flags::own_dom))
        ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
        : 0);

      ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
      const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (f & ::xml_schema::Flags::keep_dom)
        doc.setUserData (::xml_schema::dom::tree_node_key,
                         (c.get () ? &c : &d),
                         0);

      if (n.name () == "datumPlane" &&
          n.namespace_ () == "http://www.cadseer.com/prj/srl")
      {
        ::std::unique_ptr< ::prj::srl::FeatureDatumPlane > r (
          ::xsd::cxx::tree::traits< ::prj::srl::FeatureDatumPlane, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "datumPlane",
        "http://www.cadseer.com/prj/srl");
    }
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace prj
{
  namespace srl
  {
    void
    operator<< (::xercesc::DOMElement& e, const DatumPlanePlanarOffset& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // faceId
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "faceId",
            e));

        s << i.faceId ();
      }

      // offset
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "offset",
            e));

        s << i.offset ();
      }
    }

    void
    operator<< (::xercesc::DOMElement& e, const DatumPlanePlanarCenter& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // faceId1
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "faceId1",
            e));

        s << i.faceId1 ();
      }

      // faceId2
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "faceId2",
            e));

        s << i.faceId2 ();
      }
    }

    void
    operator<< (::xercesc::DOMElement& e, const DatumPlanePlanarParallelThroughEdge& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // faceId
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "faceId",
            e));

        s << i.faceId ();
      }

      // edgeId
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "edgeId",
            e));

        s << i.edgeId ();
      }
    }

    void
    operator<< (::xercesc::DOMElement& e, const SolverChoice& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // offset
      //
      if (i.offset ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "offset",
            e));

        s << *i.offset ();
      }

      // center
      //
      if (i.center ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "center",
            e));

        s << *i.center ();
      }

      // parallelThroughEdge
      //
      if (i.parallelThroughEdge ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "parallelThroughEdge",
            e));

        s << *i.parallelThroughEdge ();
      }
    }

    void
    operator<< (::xercesc::DOMElement& e, const FeatureDatumPlane& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // featureBase
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "featureBase",
            e));

        s << i.featureBase ();
      }

      // solverChoice
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "solverChoice",
            e));

        s << i.solverChoice ();
      }
    }

    void
    datumPlane (::std::ostream& o,
                const ::prj::srl::FeatureDatumPlane& s,
                const ::xml_schema::NamespaceInfomap& m,
                const ::std::string& e,
                ::xml_schema::Flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0);

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::datumPlane (s, m, f));

      ::xsd::cxx::tree::error_handler< char > h;

      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
      }
    }

    void
    datumPlane (::std::ostream& o,
                const ::prj::srl::FeatureDatumPlane& s,
                ::xml_schema::ErrorHandler& h,
                const ::xml_schema::NamespaceInfomap& m,
                const ::std::string& e,
                ::xml_schema::Flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0);

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::datumPlane (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    datumPlane (::std::ostream& o,
                const ::prj::srl::FeatureDatumPlane& s,
                ::xercesc::DOMErrorHandler& h,
                const ::xml_schema::NamespaceInfomap& m,
                const ::std::string& e,
                ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::datumPlane (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    datumPlane (::xercesc::XMLFormatTarget& t,
                const ::prj::srl::FeatureDatumPlane& s,
                const ::xml_schema::NamespaceInfomap& m,
                const ::std::string& e,
                ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::datumPlane (s, m, f));

      ::xsd::cxx::tree::error_handler< char > h;

      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
      }
    }

    void
    datumPlane (::xercesc::XMLFormatTarget& t,
                const ::prj::srl::FeatureDatumPlane& s,
                ::xml_schema::ErrorHandler& h,
                const ::xml_schema::NamespaceInfomap& m,
                const ::std::string& e,
                ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::datumPlane (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    datumPlane (::xercesc::XMLFormatTarget& t,
                const ::prj::srl::FeatureDatumPlane& s,
                ::xercesc::DOMErrorHandler& h,
                const ::xml_schema::NamespaceInfomap& m,
                const ::std::string& e,
                ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::datumPlane (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    datumPlane (::xercesc::DOMDocument& d,
                const ::prj::srl::FeatureDatumPlane& s,
                ::xml_schema::Flags)
    {
      ::xercesc::DOMElement& e (*d.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == "datumPlane" &&
          n.namespace_ () == "http://www.cadseer.com/prj/srl")
      {
        e << s;
      }
      else
      {
        throw ::xsd::cxx::tree::unexpected_element < char > (
          n.name (),
          n.namespace_ (),
          "datumPlane",
          "http://www.cadseer.com/prj/srl");
      }
    }

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
    datumPlane (const ::prj::srl::FeatureDatumPlane& s,
                const ::xml_schema::NamespaceInfomap& m,
                ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::serialize< char > (
          "datumPlane",
          "http://www.cadseer.com/prj/srl",
          m, f));

      ::prj::srl::datumPlane (*d, s, f);
      return d;
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

